server:
  port: 8002
spring:
  application:
    name: cloud-eureka-provider
eureka:
  client:
    service-url:
      # 注册中心的地址
      defaultZone: http://localhost:7001/eureka


  instance:
    instance-id: cloud-eureka-provider-8002